= GitOps - Cluster Governance
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

GitOps. 

toc::[]

== Overview

This projects represents the main IT architecture/governance configuration for managing a cluster which serves as platform for various teams with different Kubernetes/OpenShift capabilities. Using the GitOps approach.

== Prerequisites

* Kubernetes Cluster
* Helm v3 and Kustomize

== Setup

* Install ArgoCD / OpenShift GitOps (usually part of the cluster provisioning)
* Apply the bootstrap `ApplicationSet`

----
$ helm template a 00_bootstrap/01_gitops --output-dir=work/gitops
wrote work/gitops/gitops-cluster-gov-gitops/templates/02-gitops.yaml
wrote work/gitops/gitops-cluster-gov-gitops/templates/02-gitops.yaml

$ oc apply -f work/gitops/gitops-cluster-gov-gitops/templates/02-gitops.yaml
subscription.operators.coreos.com/openshift-gitops created
----

----
$ helm template a 00_bootstrap/02_init --output-dir=work/init
wrote work/init/gitops-cluster-gov-bootstrap/templates/argocd-app-bootstrap.yaml

$ oc apply -f work/init/gitops-cluster-gov-bootstrap/templates/argocd-app-bootstrap.yaml
applicationset.argoproj.io/as-overall-bootstrap created
----

== Workflow

.Create a new version and bind the version to the tag
----
$ git tag -a release-aurora -m "Release Aurora" 
$ git push origin release-aurora

$ # update version.yaml 
$ git push
----

== Summary

GitOps and IT-Governance to manage a Kubernetes/OpenShift cluster which serves as platform and foundation for the requirments of the teams. 


== References

* ArgoCD - link:https://argo-cd.readthedocs.io/en/stable/[]
* Managing GitOps control planes for secure GitOps practices - link:https://developers.redhat.com/articles/2021/08/03/managing-gitops-control-planes-secure-gitops-practices[]

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.