apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # reference to the original capability
  - ../../../../02_capabilities/applications/custom-app

# Patch/Enhance the capability for the cluster specific needs
configMapGenerator:
- name: custom-config
  behavior: merge
  files:
  - cm-specific.yaml
