apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - patch-tekton-config.yaml

patchesJSON6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: openshift-pipelines-operator-rh
      namespace: pipelines-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'pipelines-1.9'
