- op: replace
  path: /spec/generators/0/matrix/generators/0/git/files/0/path
  value: 01_config/clusters/amsterdam/cluster.yaml
- op: replace
  path: /spec/generators/0/matrix/generators/0/git/repoURL
  value: https://github.com/ocp-universe/gitops-cluster-governance.git
- op: replace
  path: /spec/generators/0/matrix/generators/1/merge/generators/0/git/repoURL
  value: https://github.com/ocp-universe/gitops-cluster-governance.git
- op: replace
  path: /spec/generators/0/matrix/generators/1/merge/generators/1/git/repoURL
  value: https://github.com/ocp-universe/gitops-cluster-governance.git
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/ocp-universe/gitops-cluster-governance.git
  