apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-rh-operators-snapshot-pipelines
  namespace: openshift-marketplace
spec:
  displayName: Custom Pipelines
  image: 'quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog:REPLACE_ME'
  publisher: Red Hat AgnosticD
  sourceType: grpc
