apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: as-core-eso-operator
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: REPLACE_ME_URL
          revision: HEAD
          files:
          - path: REPLACE_ME_CLUSTER_YAML
      - merge:
          generators:
          - git:
              repoURL: REPLACE_ME_URL
              revision: HEAD
              files:
              - path: 01_config/versions/{{ cluster.platform_version }}/version.yaml
          - git:
              repoURL: REPLACE_ME_URL
              revision: HEAD
              files:
              - path: 01_config/clusters/{{ cluster.name }}/cluster.yaml
          mergeKeys:
          - versions
  template:
    metadata:
      name: core-eso-operator
    spec:
      project: default
      source:
        repoURL: REPLACE_ME_URL
        targetRevision: "{{ versions.applications.external_secrets.revision }}"
        path: 02_capabilities/applications/external-secrets-operator
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 10s
            factor: 1
            maxDuration: 5m
          limit: 10
