apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: CatalogSource
      name: "custom-rh-operators-snapshot-pipelines"
    patch: |-
      - op: replace
        path: /spec/image
        value: "quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog:v4.10_2022_06_06"

commonAnnotations:
  acme.com/catalog-version: v4.10_2022_06_06
