apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: as-core-wave-0
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: REPLACE_ME_URL
          revision: HEAD
          files:
          - path: REPLACE_ME_CLUSTER_YAML
      - merge:
          generators:
          - git:
              repoURL: REPLACE_ME_URL
              revision: HEAD
              files:
              - path: 01_config/versions/{{ cluster.platform_version }}/version.yaml
          - git:
              repoURL: REPLACE_ME_URL
              revision: HEAD
              files:
              - path: 01_config/clusters/{{ cluster.name }}/cluster.yaml
          mergeKeys:
          - versions
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: core-wave-0
    spec:
      project: default
      source:
        repoURL: REPLACE_ME_URL
        targetRevision: "{{ version.revision }}"
        path: 01_config/clusters/{{ cluster.name }}/waves
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
