apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secret

resources:
- namespace.yaml
- controller.yaml

# OpenShift related
patchesJSON6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: sealed-secrets-controller
    patch: |-
      - op: remove
        path: /spec/template/spec/securityContext